### ISSUE TITLE
Not working with MODEL: viomi.vacuum.v10

### ISSUE THREAD

**Issue by sheminasalam** [tromarek1/-lovelace-xiaomi-styj02ym-vacuum-map-card#2]
I have tried this card with my new MODEL: viomi.vacuum.v10 but it is not working. Any ideas...

**Comment by tromarek1** [comment]
try to install it first: 
https://github.com/nqkdev/home-assistant-vacuum-styj02ym
Check if it works without my plugin. If not, the "Lovelace Xiaomi styj02ym vacuum map card" plugin will not work.

**Comment by sheminasalam** [comment]
I have integrated it to HA using this styj02ym integration but there again I am not able to use the clean_point and clean_zone services. It works but the coordinates of the vacuum are messed up. I called the service for clean point with the point: [1, -1] and instead of cleaning the point, my robot cleaned a square area including that point. Also when I gave the same command again, it corrupted its map and location sense. The dock location was misplaced to another room and to solve this i had to reboot the device.

**Comment by tromarek1** [comment]
Clean point service is for cleaning the surface around the selected point. I don't understand what the exact problem is. Could you please add some pictures or screenshot?

**Comment by sheminasalam** [comment]
The first image shows the actual true layout of my vacuum map. 
![1](https://user-images.githubusercontent.com/45196177/103172833-5ab6b500-487c-11eb-8484-5dbe4a734e59.jpg)
When I call clean_point with data ```entity_id: vacuum.robo_vacuum
point: [1,-1] ```, at the very next instance the map of my devices shifts to the second image. Here we can see that the docking position has been changed and also the robot is reporting wrong position.
![2](https://user-images.githubusercontent.com/45196177/103172841-61ddc300-487c-11eb-863a-c8245657d2e2.jpg)
To get the correct map again, I have to manually reboot the device.

**Comment by tromarek1** [comment]
It looks like problem with miio integration, not lovelace vacuum map card. Try to ask a question here: https://github.com/nqkdev/home-assistant-vacuum-styj02ym

**Comment by sheminasalam** [comment]
ok

**Comment by sheminasalam** [comment]
> It looks like problem with miio integration, not lovelace vacuum map card. Try to ask a question here: https://github.com/nqkdev/home-assistant-vacuum-styj02ym

I am a little confused with my vacuum. I see that there are a few versions of the robot: STYTJ02YM (or STYJ02YM) — Chinese version, SKV4109GL (international black), and SKV4110GL (international white). My robot maybe SKV4109GL. There is some small differences in these models. For eg: My robot doesn't support multiple maps for now but STYTJ02YM  does. Can you advise any ways to tackle the issue with miio integration?
